### PR TITLE
fix: use sha256 hash as federated identity credential name

### LINKED ISSUE #323: follow up on the char limitation for federated identity credential name.
Service account name can be at most 253 chars and namespace can be at most 63 chars. All this compounded can be long in the max scenario.

Not a blocker for this PR but I think we should follow up on the char limitation for federated identity credential name.

_Originally posted by @aramase in https://github.com/Azure/azure-workload-identity/pull/317#discussion_r784260314_

### PR DESCRIPTION
**Pull request by chewong**
**Reason for Change**:

Fixes #323. 

The name of the federated identity credential is limited 120 characters according to the Azure Portal. Use uuid in the case of 
fic name exceeding 120 characters.

**Requirements**

- [x] squashed commits
- [ ] included documentation
- [x] added unit tests and e2e tests (if applicable).

**Issue Fixed**:

**Please answer the following questions with yes/no**:

Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?

- [ ] yes
- [ ] no

**Notes for Reviewers**:

### CODE REVIEW

File: pkg/cmd/serviceaccount/create.go [hunk 1]
```diff
@@ -50,7 +51,7 @@ func newCreateCmd(authProvider auth.Provider) *cobra.Command {
 	createRunner.AppendPhases(
 		phases.NewAADApplicationPhase(),
 		phases.NewServiceAccountPhase(),
-		phases.NewFederatedIdentityPhase(),
+		phases.NewFederatedIdentityPhase(uuid.New().String),
```
Comment (aramase) [inline pkg/cmd/serviceaccount/create.go:54]: The only drawback with using an `uuid` for every request is we can end up creating a fic for same <namespace, name, issuer> when the command is run multiple times with different uid as name. Should we generated a name deterministically based on `<namespace, name, issuer>` tuple that's expected to be unique for an app?

Comment (chewong) [reply pkg/cmd/serviceaccount/create.go]: That's fair. Updated the PR.

**Review by aramase — APPROVED** [review]
