### PR TITLE
fix: generate federated identity credential name based on service account

### LINKED ISSUE #290: `azwi serviceaccount create phase federated-identity` does not append to the list of existing federated identities
**Describe the bug**

1. `azwi serviceaccount create phase federated-identity ...` to an existing federated identity
2. `az rest --method GET --uri "https://graph.microsoft.com/beta/applications/${APPLICATION_OBJECT_ID}/federatedIdentityCredentials"`
3. FIC from step 1 did not get appended to the list of existing FIC

**Expected behavior**

FIC from step 1 should be appended to the existing list of FIC. I tried with `az rest --method POST --uri "https://graph.microsoft.com/beta/applications/${APPLICATION_OBJECT_ID}/federatedIdentityCredentials" --body @body.json` and it does get appended.

### PR DESCRIPTION
**Pull request by chewong**
Signed-off-by: GitHub <noreply@github.com>

**Reason for Change**:

Fixes #290. This PR will allow `azwi` to append new federated identity credential to a list of existing one.

**Requirements**

- [x] squashed commits
- [ ] included documentation
- [ ] added unit tests and e2e tests (if applicable).

**Issue Fixed**:

**Please answer the following questions with yes/no**:

Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?

- [ ] yes
- [ ] no

**Notes for Reviewers**:

### CODE REVIEW

File: pkg/cmd/serviceaccount/phases/create/federatedidentitycredential.go [hunk 1]
```diff
@@ -66,6 +67,7 @@ func (p *federatedIdentityPhase) run(ctx context.Context, data workflow.RunData)
 
 	serviceAccountNamespace, serviceAccountName := createData.ServiceAccountNamespace(), createData.ServiceAccountName()
 	subject := util.GetFederatedCredentialSubject(serviceAccountNamespace, serviceAccountName)
+	name := strings.Join([]string{createData.ServiceAccountNamespace(), createData.ServiceAccountName(), util.GetIssuerHash(createData.ServiceAccountIssuerURL())}, "-")
```
Comment (aramase) [inline pkg/cmd/serviceaccount/phases/create/federatedidentitycredential.go:70]: Service account name can be at most 253 chars and namespace can be at most 63 chars. All this compounded can be long in the max scenario.

Not a blocker for this PR but I think we should follow up on the char limitation for federated identity credential name.

**Review by aramase — APPROVED** [review]
